defaults:
  - _self_
  - env: env_im_eval
  - learning: im_mlp
  - run: eval_run

notes: "Default Notes"
project: myohuman
exp_name: &exp_name myohuman_motion_imitation_eval
headless: False
seed: 0
no_log: False
resume_str: null
num_threads: 1
test: False 
project_root: ${hydra:runtime.cwd}
output_dir: ${project_root}/models/${exp_name}
epoch: -1
im_eval: True
num_primitive: 3
num_experts: 3

hydra:
  job:
    name: ${exp_name}
    env_set:
      OMP_NUM_THREADS: 1
  run:
    dir: ${output_dir}
